---
title: "Prediction check-in model Yelp dataset [Prediction - SVM]"
output: html_notebook
---
Taller final Aprendizaje de Maquinas
Brayan Valle Jaramillo
Laura Ospina
```{r}
setwd("E:/Courses/R/yelp-checkin-prediction-model/src/svm/")
```

```{r}
library(e1071)
library (zoo)
library (hydroGOF)

set.seed(1000)
```

```{r}
training_data <- read.csv("../../data/training_data.csv", header = TRUE , sep = ",")
test_data <- read.csv("../../data/test_data.csv" , header = TRUE , sep = ",")
```

```{r}
print(c("training_data size", nrow(training_data)))
print(c("test_data size", nrow(test_data)))
```

#SVM Model

```{r}
model <- svm(checkins ~ ., data=training_data )
summary(model)
```

#Predictions with training data
```{r}
pred_training <- predict(model , training_data)
```
Error
```{r}
p <- as.integer(pred_training)
a <- training_data$checkins
mae_R <- mae(p,a)
rmse_R <- rmse(p,a)

print(c("mae_R", mae_R))
print(c("rmse_R", rmse_R))

```


#Checking prediction with Test Data
```{r}
pred_test <- predict(model , test_data)

test_data
```

```{r}
p1 <- as.integer(pred_test)
a1 <- test_data$checkins
mae_R <- mae(p1 , a1)
rmse_R <- rmse(p1, a1)

print(c("mae_R", mae_R))
print(c("rmse_R", rmse_R))
```

```{r}
table(real = test_data[, "checkins"], prediccion = as.integer(pred_test))
```

