---
title: "Prediction check-in model Yelp dataset [Prediction - Random Forest]"
output: html_notebook
---

```{r}
setwd("E:/Courses/R/yelp-checkin-prediction-model/src/randomForest/")
```

#Install required libs

```{r}
install.packages("e1071")
install.packages("randomForest")
```

#Load required libs

```{r}
library(e1071)
library(randomForest)
library (zoo)
library (hydroGOF)
```
```{r}
set.seed(100)
```


#Load traning and test data

```{r}

training_data <- read.csv("../../data/training_data.csv", header = TRUE , sep = ",")
test_data <- read.csv("../../data/test_data.csv" , header = TRUE , sep = ",")
```
#View data size

```{r}
print(c("training_data size", nrow(training_data)))
print(c("test_data size", nrow(test_data)))
```

#Random forest model 
```{r}
model <- randomForest(checkins ~ ., data=training_data)
```

#Prediction vector 
```{r}
training_data_pred <- predict(model , training_data)
```

#Dataframe of the prediction vector
```{r}
df<-data.frame(training_data_pred)
```

```{r}
df$checkins<-rownames(training_data$checkins)
```

```{r}
alldata<-merge(training_data, df)
```

```{r}
dataframe_subset <- data.frame(subset(alldata, select=c("checkins","checkins", "training_data_pred"))) 
```

```{r}
plot(alldata$checkins, alldata$training_data_pred)
abline(1,1)

```


```{r}
x<-  training_data_pred
y<- as.integer(training_data$checkins)
mae_R <- mae (x, y)
rmse_R <- rmse (x, y)

```

```{r}
print(c("mae_R", mae_R))
print(c("rmse_R", rmse_R))
```
#Test data

```{r}
test_data_pred <- predict(model, test_data)

```
Data frame from pred vector
```{r}
df <- data.frame(test_data_pred)
```

Add a colum to dataset with checkins
```{r}
df$checkins <- rownames(test_data$checkins)
```
New datframe with checkins pred
```{r}
all_data <- merge(test_data , df)
```
Data frame containing checkin model with real and predic values
```{r}
dataframe_subset <- data.frame(subset(all_data , select =c("checkins" , "checkins" , "test_data_pred")))
```

Plot data

```{r}
plot(all_data$checkins, all_data$test_data_pred)
abline(1,1)
```

Error

```{r}
x<-  test_data_pred
y<- as.integer(test_data$checkins)
mae_R <- mae (x, y)
rmse_R <- rmse (x, y)
```
```{r}
print(c("mae_R", mae_R))
print(c("rmse_R", rmse_R))
```

