---
title: "Prediction check-in model Yelp dataset"
#output: rmarkdown::github_document
output: html_notebook
---


```{r}
setwd("E:/Courses/R/yelp-checkin-prediction-model/src/")
```
#Required libraries
```{r}
library(tidyverse)
library(dplyr)
```


#Read the dataset
```{r}
fullData <- read.csv(file="../data/CheckinBusiness_DatosCompletos.csv", header=TRUE, sep=",")
```
#View data
```{r}
head(fullData)
```
#Converting into tibble data frame
```{r}
filteredData <- as_tibble(fullData)
filteredData
```


#Selecting subset data for for all business in Phoenix city
```{r}
filteredData <- filteredData %>% filter(city == "Phoenix")
```
#Remove columns: [Row number, city, day_tile]

```{r}
filteredData <- filteredData %>% select(stars , review_count , is_open ,week_day,hourofday,checkins)
filteredData
```

#Recoding Week day to the asociative day of week
```{r}
filteredData$week_day <-recode(filteredData$week_day,'Sun'=1, 'Mon'=2, 'Tue'=3, 'Wed'=4 , 'Thu'=5, 'Fri'=6,'Sat'=7)
filteredData
write.csv(filteredData , file ="../data/filtered_data.csv")

```
#Select 70% for traning data
```{r}
training_data_size <- ceiling(nrow(filteredData)*0.7)
training_data_size
```

#Get training data

```{r}
training_data <- filteredData[0:training_data_size,]
```
#Save training data to a csv file

```{r}
write.csv(training_data , file ="../data/training_data.csv")
```
#Get Test data
```{r}
test_data <- filteredData[(training_data_size+1):nrow(filteredData),]
```

#Save Test data to a csv file

```{r}
write.csv(test_data , file ="../data/test_data.csv")
```


```{r}

```

